# Configuration file for CLANS
# Each line contains a key-value pair in the format -<key> <value>.
# Lines starting with '#' are comments and will be ignored.
-nographics T
-load /home/aronw/Development/Clans-3D/Scores_Evaluation/50_cleaned_seq.clans
-dorounds 100000
-saveto /home/aronw/Development/Clans-3D/Scores_Evaluation/50_cleaned_seq_clustered_r_100000_p_1e-10.clans
-pval 1e-10
-verbose 1
